name:                advent-calendar-bot
version:             0.2.0
github:              "rodbb/advent-calendar-bot"
license:             BSD3
author:              "amderbar"
maintainer:          "amderbar@gmail.com"
copyright:           "2021 rodbb"

extra-source-files:
- README.md
- ChangeLog.md

data-files:
- templates/*

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/advent-calendar-bot#readme>

default-extensions:
- OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- connection
- containers
- feed
- http-client
- http-client-tls
- mtl
- modern-uri
- mustache
- req
- parsec
- string-conversions
- text
- text-show
- time
- transformers
- xml-conduit

library:
  source-dirs: src

executables:
  advent-calendar-bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - advent-calendar-bot
    - optparse-applicative

tests:
  advent-calendar-bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - advent-calendar-bot
