name: Build Application

on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]
    defaults:
      run:
        shell: ${{ (matrix.os == 'windows-latest' && 'bash') || 'sh' }}
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@main
      name: Setup Haskell
      with:
        ghc-version: '8.10.7'
        enable-stack: true
        stack-version: 'latest'
    - name: Stack Root
      id: stack-root
      run: echo ::set-output name=path::$(stack --system-ghc path --stack-root)
    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ${{ steps.stack-root.outputs.path }}
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies
    - name: Build and Test
      run: stack --system-ghc test --copy-bins --local-bin-path=./advent-calendar-bot

    - name: Compress
      id: compress
      run: |
        zipname=advent-calendar-bot-${{ runner.OS }}
        zip -r ${zipname} advent-calendar-bot
        echo ::set-output name=path::${zipname}.zip
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        files: ${{ steps.compress.outputs.path }}
