name: Build Application

on:
  push:
    tags: ['v*.*.*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest] #, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ~/.stack
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: haskell/actions/setup@main
      name: Setup Haskell
      with:
        ghc-version: '8.10.7'
        enable-stack: true
        stack-version: 'latest'
    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies
    - name: Build and Test
      run: stack --system-ghc test --copy-bins --local-bin-path=./bin

    - name: Windows Artifact Extension
      id: extension
      if: matrix.os == 'windows-latest'
      run: echo ::set-output name=ext::.exe
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        files: ./bin/advent-calendar-bot-exe${{ steps.extension.outputs.ext }}
