name: Test Application

on:
  push: [branches]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest]

    defaults:
      run:
        shell: ${{ (matrix.os == 'windows-latest' && 'bash') || 'sh' }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Haskell
      id: setup-haskell
      uses: haskell/actions/setup@main
      with:
        ghc-version: '9.0.2'
        enable-stack: true
        stack-version: 'latest'

    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v3
      with:
        path: ${{ steps.setup-haskell.outputs.stack-root }}
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-
          ${{ runner.os }}-stack-

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies

    - name: Build and Test
      run: stack --system-ghc test
