name: Test Application

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@main
      name: Setup Haskell
      with:
        ghc-version: '9.0.2'
        enable-stack: true
        stack-version: 'latest'
    - name: Set STACK_ROOR env
      run: echo "STACK_ROOT=$(stack --system-ghc path --stack-root)" >> $GITHUB_ENV
    - name: Cache .stack
      id: cache-stack
      uses: actions/cache@v2
      with:
        path: ${{ env.STACK_ROOT }}
        key: ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-${{ hashFiles('**/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-${{ hashFiles('**/stack.yaml.lock') }}-
          ${{ runner.os }}-stack-

    - name: Install dependencies
      run: stack --system-ghc test --only-dependencies
    - name: Build and Test
      run: stack --system-ghc test
